### ISSUE TITLE
Question: how to use interrupt?

### ISSUE THREAD

**Issue by rdehuyss** [mcauser/micropython-pcf8574#1]
Hi,

First of all, thanks for this great library! 

I do have a question - I don't understand how to use the interrupts. Could you please provide an example?

I would expect a callback to be called with the pin that changed and it's new value.

Thanks in advance,
Ronald

**Comment by rdehuyss** [comment]
Never mind - I thought I could be notified via the I2C bus. If I understand correctly, I need to use another gpio pin that is connected to the interupt pin of the pcf-8574.

**Comment by mcauser** [comment]
Yes, that is correct. It doesn't notify over I2C.
Just uses that extra INT pin, broken out on some boards, which you can listen for changes on.

The INT pin requires a pull-up resistor and when the chip detects a change, will drive the pin low.

**Comment by rdehuyss** [comment]
Thx!
