### ISSUE TITLE
Input Mask Modification

### ISSUE THREAD

**Issue by TDStrasser** [mcauser/micropython-pcf8574#2]
Thanks for the useful module script. In using it (on a RP2040) I discovered that when writing an output, the script will also write back the states of all other pins.  That is, where any pins are designated as inputs and set to high, and are driven low by, say, a pushbutton, and one simultaneously activates a pin as an output, the pins with active inputs have their state written back, thereby effectively disabling them as input pins.  This took a while to deduce as I was getting some very odd results when using this chip.
The solution is to define an input mask byte (0 = output, 1 = input) passing that as an argument when initialising the chip object.  A function to change the mask is also needed for the occasions when I/O is reconfigured.  In the pin setting and toggle functions, the output byte is OR'd with the input mask byte to ensure the corresponding pins retain their high output state.
The edited script is attached, if you find that of use.
[pcf8574.zip](https://github.com/mcauser/micropython-pcf8574/files/9487703/pcf8574.zip)

**Comment by mcauser** [comment]
I think I get what you mean.

eg. Push button on pin 0 connected to GND.

Set all pins high (inputs):
```
pcf.port = 0xFF
```

Press and hold pushbutton on pin 0. If port is read now, it would be 0xFE

Set pin 1 low. Internally calls _write() with state 0xFC, includes the pressed state of button 0.
```
pcf.pin(1, value=0)
```

Release button 0.

The value of port is still 0xFC, making pressing button 0 now unresponsive.

**Comment by mcauser** [comment]
When using this chip with inputs, you really want to isolate/differentiate "what you want the pins to be output as" and "what they are currently reading as".

This is what you're getting at with your input mask.

Having two _port's (wanted/actual) would give you the ability to compare them, and toggle() based on the wanted value, ignoring what its input currently is reading as.

**Comment by TDStrasser** [comment]
Thanks - that is the effect of the modified script I shared back, and that I am using.

**Comment by DrPeterRobinson** [comment]
Thanks @TDStrasser, your modification solved the problem for me.
