### ISSUE TITLE
Not sure what I am doing wrong, device is on the bus, running module code always get ETIMEDOUT response?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [mcauser/micropython-pcf8574#3]
Using MicroPython 1.24.  Copied the pcf8574.py file into my ESP32 module, happen to be using thonny IDE.  Run the following code...
```
import pcf8574
from machine import I2C

#
theI2C = I2C(0)
thePCF8574 = pcf8574.PCF8574(theI2C, 0x20)

thePCF8574.pin(2)
```
Just trying to read pin 2 for example.  And I get the following error...
```
Traceback (most recent call last):
  File "<stdin>", line 51, in <module>
  File "pcf8574.py", line 36, in pin
  File "pcf8574.py", line 56, in _read
OSError: [Errno 116] ETIMEDOUT
```
I know the device is on the i2c bus...
```
theI2C.scan()
[32]
```
So not sure what I am doing wrong?

**Comment by mcauser** [comment]
`ETIMEDOUT` happens when the device isn't found on the bus, or doesn't respond in time.
Does `.scan()` always show `[32]` or sometimes `[]`?
Does every pin read fail, or intermittently fails?
There's also a `.check()` method for scanning the bus and raising if not found.
I'd check the cables, pull-up resistors. Try adding a 2nd device on the I2C bus.

**Comment by Jibun-no-Kage** [comment]
Will test and report back.

The PCF8574 board appears to have the pull-up resisters in place.  It is the only device on the bus at this time as well.  Using the same ESP32 module, cables and power supply I can read other sensors, for example VEML6040 or a TCS34725.  But that all of this could work at one point and fail later, if I have some bad quality jumpers in use.

**Comment by Jibun-no-Kage** [comment]
Confirmed the board has pull-ups.  By default if I am reading the datasheet right, all pins are set to high on power up... but added code to ensure this.  Once I put some test load on the pins, tracked down the issue, ground was not consistently connected, bad jumper.  So it was impacting the communication consistency as well as function of pin state.
